# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ec21133dd84a27aa42588297b0fa774978a9dfd4a42e2fd4d7167c58e23f7cb79bfa469c3fcb38af9e204b91b31cb1a698a3997168dea0383594f9129979664

test:
  secret_key_base: fbe837e5043bea2f69d0e0c8b445fbd1099ba80bfb3b6e719327e487efd0792994b405c1ad575ff05faec682a02f8c39481ddef0330bf74fe1b64e3597131b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
