# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9ef99304c531aadf2b0b795c609df97f415b72bbc6f9b9df005ea242fd3177093951d12253cde1ba351e8f46cf1478d714c75f68be47bcea42127ebc6c86263

test:
  secret_key_base: d15904d7cde1eaf269a93789936aa420645d55671ee340059ec802c28489b204b7406ec2bee62c75b2adeae3e7538c3436f64b8c8ea8bf60aaf2480067073fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
